- name: creation of ec2 and r53
  hosts: local
  become: yes
  connection: local
  vars:
    ansible_python_interpreter: /usr/bin/python3
    ami_id: ami-0220d79f3f480ecf5
    sg_id: sg-08ab4d82756ecaa18 # replace with your SG ID
    zone_id: "Z03213491OV18327UWTE0" # replace with your route53 zone ID
    domain_name: "countryroot.fun"
    instances:
      - mongodb
  tasks: 
  - name: create an ec2-instance    
    amazon.aws.ec2_instance:
      name: "{{ item }}"
      instance_type: t3.micro
      security_group: "{{ sg_id }}"
      image_id: "{{ ami_id }}"
      tags:
        Name: "{{ item }}"
    loop: "{{ instances }}"
    register: ec2_instance
  