- name: creation of ec2 and r53
  hosts: local
  connection: local
  vars:
    ansible_python_interpreter: /usr/bin/python3
    region: us-east-1
    ami_id: ami-0220d79f3f480ecf5
    sg_id: sg-08ab4d82756ecaa18
    zone_id: "Z03213491OV18327UWTE0"
    domain_name: "countryroot.fun"
    instances:
      - mongodb

  tasks:
    - name: create an ec2-instance
      amazon.aws.ec2_instance:
        name: "{{ item }}"
        instance_type: t3.micro
        image_id: "{{ ami_id }}"
        region: "{{ region }}"
        security_group: "{{ sg_id }}"
        tags:
          Name: "{{ item }}"
      loop: "{{ instances }}"
      register: ec2_instance
