- name: mysql-server setup
  hosts: mysql
  become: yes
  tasks:
  - name: install mysql server
    ansible.builtin.package:
      name: mysql-server
      state: present
  
  - name: enable and start the mysql service
    ansible.builtin.service:
      name: mysqld
      enabled: yes
      state: started

  - name: setting up the password
    ansible.builtin.command:  mysql_secure_installation --set-root-pass RoboShop@1